### ISSUE TITLE
Potential small fixes / enhancements

### ISSUE THREAD

**Issue by DamienCarpy** [claranet/terraform-azurerm-app-gateway#1]
Hello all, first thanks a lot for all this solid work 😊
While I was trying your app gw module, I noticed a couple of things that didn't work... either I didn't understand how they were meant to work, or they may be fixed for a more "universal" way of using the module.
1. In the `request_routing_rule` dynamic block, `http_listener_name`, `backend_address_pool_name` and `backend_http_settings_name` arguments use a nested lookup searching for the `name` key as default value, causing an error at apply time when these arguments are not set in input (typically : when using a redirect configuration in conjunction with the request routing rule). They'd all better be set to `null` as default.

Here's the input example:

``` >
 appgw_routings = [{
    name                        = "${local.BlockCoreName}-routing-http"
    rule_type                   = "Basic"
    http_listener_name          = "${local.BlockCoreName}-listener-http"
    redirect_configuration_name = "${local.BlockCoreName}-redirect"
  }]
```

Here's the error the Azure API threw at Terraform when trying to apply as-is:

> Error: Error expanding `request_routing_rule`: Conflict between `backend_address_pool_name` and `redirect_configuration_name` (back-end pool not applicable when redirection specified)

2. In the `path_rule` nested dynamic block from `url_path_map dynamic` block, the `paths` argument won't accept a list of strings as value. Removing brackets around the lookup function solves it easily.

Are these suggestions relevant for you, or did I miss understanding the correct use of the module ?

**Comment by Shr3ps** [comment]
Hello,

Thanks for this feedback. I think I have some answers for you:

1. Indeed our module is designed with our default use-case which is using a backend pool. If you want to use redirect, here is what you can try:
```hcl
appgw_routings = [{
    name                        = "${local.BlockCoreName}-routing-http"
    rule_type                   = "Basic"
    http_listener_name          = "${local.BlockCoreName}-listener-http"
    redirect_configuration_name = "${local.BlockCoreName}-redirect"

    backend_address_pool_name = null
    backend_http_settings_name  = null
  }]
```
Don't hesitate to open a PR on the README is this is not explicit enough (maybe enrich the usage/example part).

2. You're right, I think this is probably an old implementation of the module with old version of Terraform. Feel free to open a PR to fix this!

**Comment by DamienCarpy** [comment]
Thanks for your reply, it totally makes sense to me. I'll definitely take time in the following days to open a PR :-)

**Comment by Shr3ps** [comment]
@DamienCarpy should we close this issue? or do you want to keep it for your future PR?

**Comment by DamienCarpy** [comment]
@Shr3ps Sadly I'm too busy to present you a PR now :-/ So you can safely close this issue :-)

**Comment by Shr3ps** [comment]
We released a new version that handle some of the issues you had.
